jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv
      - name: Run importer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSV_PATH: ${{ github.workspace }}/${{ inputs.csv_path }}
          PROJECT_OWNER: ${{ inputs.project_owner }}
          PROJECT_NUMBER: ${{ inputs.project_number }}
          REPO: ${{ inputs.repo_full }}
        run: |
          python import_issues_to_project.py
